---
booktitle: Proceedings of the Second Teaching Machine Learning and Artificial Intelligence
  Workshop
shortname: TeachML
year: '2021'
volume: '170'
start: 2021-09-08
end: 2021-09-13
published: 2022-03-14
conference_number: '02'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: TeachML-2021
month: 0
cycles: false
bibtex_editor: Kinnaird, Katherine M. and Steinbach, Peter and Guhr, Oliver
editor:
- given: Katherine M.
  family: Kinnaird
- given: Peter
  family: Steinbach
- given: Oliver
  family: Guhr
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Second Teaching Machine Learning and Artificial Intelligence Workshop
    Held in Virtual Conference on 08-13 September 2021

  Published as Volume 170 by the Proceedings of Machine Learning Research on 14 March 2022.

  Volume Edited by:
    Katherine M. Kinnaird
    Peter Steinbach
    Oliver Guhr

  Series Editors:
    Neil D. Lawrence
    * Mark Reid
date_str: '08--13 Sep'
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v170"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v170
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v170
email: ''
conference:
  name: The Second Teaching Machine Learning and Artificial Intelligence
    Workshop
  url: https://teaching-ml.github.io/2021/
  location: Virtual Conference
  dates:
  - 2021-09-08
  - 2021-09-09
  - 2021-09-10
  - 2021-09-11
  - 2021-09-12
  - 2021-09-13
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v170/teachml21.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v170/teachml21.bib
